::Create DIR (@ Domen).bat

@echo off
@chcp 1251

MD "@ Aim.com"
MD "@ Aol.com"
MD "@ Att.net"
MD "@ Bellsouth.net"
MD "@ Btinternet.com"
MD "@ Charter.net"
MD "@ Comcast.net"
MD "@ Cox.net"
MD "@ Earthlink.net"
MD "@ Excite.com"
MD "@ Gmail.com"
MD "@ Gmx.de"
MD "@ Gmx.net"
MD "@ Googlemail.com"
MD "@ Hotmail.co.uk"
MD "@ Hotmail.com"
MD "@ Hotmail.es"
MD "@ Hotmail.fr"
MD "@ Hotmail.it"
MD "@ Libero.it"
MD "@ Live.co.uk"
MD "@ Live.com"
MD "@ Live.com.mx"
MD "@ Live.fr"
MD "@ Mail.com"
MD "@ Mail.ru"
MD "@ Msn.com"
MD "@ Music.msprod.msp"
MD "@ Myspace.com"
MD "@ Netscape.net"
MD "@ Netzero.com"
MD "@ None"
MD "@ Optonline.net"
MD "@ Peoplepc.com"
MD "@ Qamail.msprod.msp"
MD "@ Rocketmail.com"
MD "@ Sbcglobal.net"
MD "@ Tmail.com"
MD "@ Verizon.net"
MD "@ Web.de"
MD "@ Wp.pl"
MD "@ Yahoo.ca"
MD "@ Yahoo.co.id"
MD "@ Yahoo.co.jp"
MD "@ Yahoo.co.uk"
MD "@ Yahoo.com"
MD "@ Yahoo.com.br"
MD "@ Yahoo.com.my"
MD "@ Yahoo.de"
MD "@ Yahoo.es"
MD "@ Yahoo.fr"
MD "@ Yahoo.it"
MD "@ Ymail.com"