echo off >> @126.txt
echo off >> @163.txt
echo off >> @aim.txt
echo off >> @aol.txt
echo off >> @bk.txt
echo off >> @comcast.txt
echo off >> @free.txt
echo off >> @gmail.txt
echo off >> @gmx.txt
echo off >> @hotmail.txt
echo off >> @list.txt
echo off >> @live.txt
echo off >> @mail.ru.txt
echo off >> @msn.txt
echo off >> @naver.txt
echo off >> @online.txt
echo off >> @orange.txt
echo off >> @outlook.txt
echo off >> @qq.txt
echo off >> @rambler.txt
echo off >> @sfr.txt
echo off >> @wanadoo.txt
echo off >> @web.txt
echo off >> @yahoo.txt
echo off >> @yandex.txt
echo off >> @ymail.txt